### ISSUE TITLE
Bug: tested numbers of blocks in estimateSimpleSBM 

### ISSUE THREAD

**Issue by ChrisBotella** [GrossSBM/sbm#6]
Hello =),

I face two problems with function `estimateSimpleSBM`, when specifying the interval for the numbers of blocks to test. 

Normally, the min and max bounds should be supplied through **nbBlocksRange** (vector with two elements), of the named list **estimOptions** (argument of `estimateSimpleSBM`).

So the two problems:
1) nbBlocksRange[1] doesn't define the minimum bound. In my tests, the lower bound is always 1, and I found no way to change it.
2) The maximum bound is not always nbBlocksRange[2]. Instead, it is for instance nbBlocksRange[1] when explorFactor<=nbBlocksRange[1]<nbBlocksRange[2] ... O_o

As you can see, the two problems appear in the example below:

```
require(sbm)
nNodes = 50
adj = matrix(round(runif(nNodes,0,1)),nNodes,nNodes)
SBM = estimateSimpleSBM(adj,directed=T,estimOptions = list(nbBlocksRange=c(10,20),explorFactor=1.5))
print(SBM$storedModels$nbBlocks)
```

It would be great if we could specify the floor number (first problem), because currently the calculation time  considerably increases beyond about 20 blocks. 

PS: Sorry, I wanted to check what happens exactly, but I don't know how to access the concerned function which, I guess, is the sub-method `estimate` of the method `optimize` for class **SimpleSBM_fit**

Best Regards,

**Comment by Sophiedonnet** [comment]
Hi, 
I ckecked what you said and you are right. Our code does not take into account the bounds. I will change it next week and tell you when it is ready. 
Thanks for helping us!

**Comment by Sophiedonnet** [comment]
Hi, 
We have now corrected this bug (it should be un the master branch). 
However,  we do not control strictly the bounds (it comes from the sbmmodel). However, by tuning the bounds and the explore factor you will be able to estimate the models in the interval you want. 

require(sbm)
nNodes = 50
adj = matrix(round(runif(nNodes,0,1)),nNodes,nNodes)
SBM = estimateSimpleSBM(adj,directed=T,estimOptions = list(nbBlocksRange=c(20,30),explorFactor= 4))
print(SBM$storedModels$nbBlocks)

Can you tell me if everything works that way? 
Regards

**Comment by ChrisBotella** [comment]
Thank you for the work on this. I removed the package and re-installed from Github using devtools. 

Unfortunately, I can say that after trying your example and running some more tests, the first problem that I mentionned persist =/, namely the minimal tested number of groups is always 1, whatever the combinations of **nbBlocksRange** and **explorFactor** values. Is it a constraint of the underlying algorithm?

However, a desired maximum bound **n** can always be achieved by playing with **nbBlocksRange[2]** and **explorFactor**, e.g. specfying **nbBlocksRange[2]=n** and giving a high enough value to **explorFactor**. 

An example that works for the upper bound (based on the initial example):
``` 
require(sbm)
nNodes = 50
adj = matrix(round(runif(nNodes,0,1)),nNodes,nNodes)
SBM = estimateSimpleSBM(adj,directed=T,estimOptions = list(nbBlocksRange=c(10,20),explorFactor= 12))
print(SBM$storedModels$nbBlocks)
```

**Comment by jchiquet** [comment]
Hi @ChrisBotella ,

There is probably a misunderstanding about the meaning of the parameters in `nbBlocksRange`, and in fact about the underlying parameters passed to the package `blockmodels` that actually does the optimisation job for fitting Simple and Bipartite SBM :

The first argument in `nbBlocksRange=c(10,20)` is the minimum number of groups that will be explored and 20 is the maximum, in the following sense: it only means that, even if the ICL drops down before reaching 10, then we force the algorithm to go up to 10. And if the ICL does not drop after 20, it will be cut whatever the shape of the curve. Indeed, as you mention, the path followed by blockmodels will always start from one.

Don't known if I am clear. At some point we can speak in French though ;-)

If it is a desired feature, we may, in the future, try to modify blockmodels itself to adapt to this behavior.

Best,

**Comment by ChrisBotella** [comment]
Salut,

Ok merci c'est compris maintenant.  

Effectivement, c'est pas ce que j'avais compris à la lecture du "help". Peut être qu'être plus explicite sur ce point, comme tu viens de l'être, dans le fichier d'aide éviterait le malentendu à l'avenir.

Merci encore en tout cas!

Amicalement,

Christophe
